# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Common name of the crop (e.g. 'Maize').", max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, default='', help_text="Scientific / Latin name (e.g. 'Zea mays').", max_length=150)),
                ('category', models.CharField(blank=True, default='', help_text="Crop category (e.g. 'cereal', 'legume', 'oilseed', 'vegetable').", max_length=50)),
                ('description', models.TextField(blank=True, default='', help_text='General description of the crop.')),
                ('growing_days_min', models.PositiveSmallIntegerField(blank=True, help_text='Minimum growing period in days.', null=True)),
                ('growing_days_max', models.PositiveSmallIntegerField(blank=True, help_text='Maximum growing period in days.', null=True)),
                ('growing_days_typical', models.PositiveSmallIntegerField(blank=True, help_text='Typical growing period in days.', null=True)),
                ('planting_depth_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended planting depth in cm.', max_digits=5, null=True)),
                ('planting_spacing_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended plant spacing in cm.', max_digits=6, null=True)),
                ('seeds_per_gram', models.DecimalField(blank=True, decimal_places=2, help_text='Number of seeds per gram (for seeding rate calculation).', max_digits=8, null=True)),
                ('seeding_rate_kg_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended seeding rate in kg/ha.', max_digits=6, null=True)),
                ('optimal_temp_min', models.DecimalField(blank=True, decimal_places=1, help_text='Optimal temperature minimum (°C).', max_digits=4, null=True)),
                ('optimal_temp_max', models.DecimalField(blank=True, decimal_places=1, help_text='Optimal temperature maximum (°C).', max_digits=4, null=True)),
                ('frost_sensitive', models.BooleanField(default=True, help_text='Whether the crop is sensitive to frost.')),
                ('drought_tolerant', models.BooleanField(default=False, help_text='Whether the crop has drought tolerance.')),
                ('flood_tolerant', models.BooleanField(default=False, help_text='Whether the crop has flood tolerance.')),
                ('soil_ph_min', models.DecimalField(blank=True, decimal_places=1, help_text='Minimum preferred soil pH.', max_digits=4, null=True)),
                ('soil_ph_max', models.DecimalField(blank=True, decimal_places=1, help_text='Maximum preferred soil pH.', max_digits=4, null=True)),
                ('sunlight_hours_min', models.PositiveSmallIntegerField(blank=True, help_text='Minimum daily sunlight hours required.', null=True)),
                ('rainfall_min_mm', models.PositiveIntegerField(blank=True, help_text='Minimum rainfall required for the growing period (mm).', null=True)),
                ('rainfall_optimum_mm', models.PositiveIntegerField(blank=True, help_text='Optimum rainfall for the growing period (mm).', null=True)),
                ('rainfall_max_mm', models.PositiveIntegerField(blank=True, help_text='Maximum tolerable rainfall for the growing period (mm).', null=True)),
                ('expected_yield_min_kg_ha', models.PositiveIntegerField(blank=True, help_text='Expected minimum yield (kg/ha) under good conditions.', null=True)),
                ('expected_yield_max_kg_ha', models.PositiveIntegerField(blank=True, help_text='Expected maximum yield (kg/ha) under excellent conditions.', null=True)),
                ('expected_yield_typical_kg_ha', models.PositiveIntegerField(blank=True, help_text='Expected typical yield (kg/ha) under average conditions.', null=True)),
                ('planting_season', models.CharField(blank=True, default='', help_text="Recommended planting season (e.g. 'long rains', 'short rains', 'spring').", max_length=50)),
                ('harvest_season', models.CharField(blank=True, default='', help_text='Expected harvest season.', max_length=50)),
                ('suitable_months', models.JSONField(default=list, help_text='List of suitable months for planting (1-12).')),
                ('source', models.CharField(blank=True, default='', help_text="Source of crop data (e.g. 'FAO', 'national-agricultural-extension').", max_length=100)),
                ('source_url', models.URLField(blank=True, default='', help_text='URL of the source data if available.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this crop is available for use in the system.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'crop',
                'verbose_name_plural': 'crops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, default='', help_text="Context for these requirements (e.g. 'irrigated', 'rainfed', 'highland').", max_length=50)),
                ('soil_type', models.CharField(blank=True, default='', help_text='Recommended soil type.', max_length=50)),
                ('soil_texture', models.CharField(blank=True, default='', help_text="Recommended soil texture (e.g. 'loam', 'clay', 'sandy').", max_length=50)),
                ('nitrogen_kg_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended nitrogen application (kg/ha).', max_digits=6, null=True)),
                ('phosphorus_kg_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended phosphorus application (kg/ha).', max_digits=6, null=True)),
                ('potassium_kg_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Recommended potassium application (kg/ha).', max_digits=6, null=True)),
                ('irrigation_required', models.BooleanField(default=False, help_text='Whether irrigation is required for this crop in this context.')),
                ('irrigation_water_mm', models.PositiveIntegerField(blank=True, help_text='Recommended irrigation water amount (mm) if irrigated.', null=True)),
                ('planting_months', models.JSONField(default=list, help_text='Recommended planting months for this context.')),
                ('planting_method', models.CharField(blank=True, default='', help_text="Recommended planting method (e.g. 'direct', 'transplant', 'broadcast').", max_length=50)),
                ('source', models.CharField(blank=True, default='', help_text='Source of requirement data.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crop_requirements', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='crops.crop')),
            ],
            options={
                'verbose_name': 'crop requirement',
                'verbose_name_plural': 'crop requirements',
                'ordering': ['crop__name', 'context'],
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Variety name/cultivar (e.g. 'H614', 'SC713').", max_length=150)),
                ('breeder', models.CharField(blank=True, default='', help_text="Breeder or seed company (e.g. 'Pioneer', 'Kenya Seed Company').", max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the variety.')),
                ('maturity_days_early', models.PositiveSmallIntegerField(blank=True, help_text='Days to maturity (early estimate).', null=True)),
                ('maturity_days_late', models.PositiveSmallIntegerField(blank=True, help_text='Days to maturity (late estimate).', null=True)),
                ('maturity_days_typical', models.PositiveSmallIntegerField(blank=True, help_text='Typical days to maturity.', null=True)),
                ('yield_sd_min_kg_ha', models.PositiveIntegerField(blank=True, help_text='Expected yield range minimum (kg/ha) for this variety.', null=True)),
                ('yield_sd_max_kg_ha', models.PositiveIntegerField(blank=True, help_text='Expected yield range maximum (kg/ha) for this variety.', null=True)),
                ('yield_sd_typical_kg_ha', models.PositiveIntegerField(blank=True, help_text='Expected typical yield (kg/ha) for this variety.', null=True)),
                ('disease_resistance', models.TextField(blank=True, default='', help_text='Disease resistance profile (free text).')),
                ('pest_resistance', models.TextField(blank=True, default='', help_text='Pest resistance profile (free text).')),
                ('drought_tolerance_level', models.CharField(blank=True, default='', help_text="Drought tolerance level (e.g. 'high', 'medium', 'low').", max_length=20)),
                ('seed_color', models.CharField(blank=True, default='', help_text='Seed color (for identification).', max_length=50)),
                ('adaptation_zones', models.JSONField(default=list, help_text='Geographic/climatic zones this variety is adapted to.')),
                ('recommended_regions', models.JSONField(default=list, help_text='Recommended regions for this variety.')),
                ('is_recommended', models.BooleanField(default=False, help_text='Whether this variety is recommended by default.')),
                ('source', models.CharField(blank=True, default='', help_text='Source of variety data.', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', help_text='URL of the source data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_varieties', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(help_text='The crop this variety belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='crops.crop')),
            ],
            options={
                'verbose_name': 'variety',
                'verbose_name_plural': 'varieties',
                'ordering': ['crop__name', 'name'],
                'indexes': [models.Index(fields=['crop', 'is_recommended'], name='crops_varie_crop_id_aee065_idx')],
                'unique_together': {('crop', 'name')},
            },
        ),
    ]
