# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Farm name or identifier.', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Farm center point (WGS84 longitude/latitude).', null=True, srid=4326)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=3, help_text='Farm area in hectares.', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Free-text notes about the farm.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Farm owner / primary responsible user.', on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farm',
                'verbose_name_plural': 'farms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Region name.', max_length=200)),
                ('region_type', models.CharField(choices=[('county', 'County'), ('ward', 'Ward'), ('zone', 'Agricultural Zone'), ('custom', 'Custom Region')], default='county', help_text='Type of region.', max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Geographic boundary of the region (WGS84).', null=True, srid=4326)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the region.')),
                ('external_ref', models.CharField(blank=True, default='', help_text='External reference code.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this region.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farm region',
                'verbose_name_plural': 'farm regions',
                'ordering': ['name'],
                'unique_together': {('name', 'region_type')},
            },
        ),
        migrations.CreateModel(
            name='OfficerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('acting', 'Acting')], default='primary', help_text='Type of assignment.', max_length=50)),
                ('notes', models.TextField(blank=True, default='', help_text='Notes about this assignment.')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(help_text='Agricultural officer assigned to this region.', limit_choices_to={'role': 'officer'}, on_delete=django.db.models.deletion.CASCADE, related_name='region_assignments', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(help_text='Region the officer is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='farms.farmregion')),
            ],
            options={
                'verbose_name': 'officer assignment',
                'verbose_name_plural': 'officer assignments',
                'ordering': ['officer__username', 'region__name'],
                'unique_together': {('officer', 'region')},
            },
        ),
    ]
