# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('weather', 'Weather Report'), ('farm', 'Farm Report'), ('crop_cycle', 'Crop Cycle Report'), ('yield', 'Yield Report'), ('recommendation', 'Recommendation Report'), ('officer', 'Agricultural Officer Report'), ('system', 'System Report'), ('farmer', 'Farmer Report'), ('crop', 'Crop Report'), ('production', 'Production Report'), ('administrative', 'Administrative Report')], help_text='Type of report.', max_length=20)),
                ('title', models.CharField(help_text='Human-readable report title.', max_length=255)),
                ('filter_period_start', models.DateField(blank=True, help_text='Report date range start (inclusive).', null=True)),
                ('filter_period_end', models.DateField(blank=True, help_text='Report date range end (inclusive).', null=True)),
                ('filter_farm_ids', models.JSONField(default=list, help_text='Farm IDs included in this report (for multi-farm reports).')),
                ('filter_crop_ids', models.JSONField(default=list, help_text='Crop IDs included in this report.')),
                ('filter_farmer_ids', models.JSONField(default=list, help_text='Farmer user IDs included in this report.')),
                ('filter_status', models.CharField(blank=True, default='', help_text='Cycle/status filter applied, if any.', max_length=20)),
                ('content', models.JSONField(blank=True, help_text='Generated report content (structured data: summary, details, charts, conclusions).', null=True)),
                ('available_formats', models.JSONField(default=list, help_text='List of formats this report has been rendered to (html, pdf, csv).')),
                ('output_html', models.CharField(blank=True, default='', help_text='Path to HTML version.', max_length=500)),
                ('output_pdf', models.CharField(blank=True, default='', help_text='Path to PDF version (if generated).', max_length=500)),
                ('output_csv', models.CharField(blank=True, default='', help_text='Path to CSV version (if generated).', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Report generation status.', max_length=20)),
                ('access_level', models.CharField(choices=[('owner_only', 'Owner Only'), ('owner_and_officers', 'Owner + Assigned Officers'), ('owner_and_admin', 'Owner + Admins'), ('all_officers', 'All Agricultural Officers'), ('all_users', 'All Authenticated Users'), ('public', 'Public (no auth)')], default='owner_only', help_text='RBAC access level controlling who can view this report.', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if generation failed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the report was generated (ready/failed).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_cycle', models.ForeignKey(blank=True, help_text='Crop cycle this report is primarily about (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cycles.cropcycle')),
                ('farm', models.ForeignKey(blank=True, help_text='Farm this report is primarily about (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='farms.farm')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User who generated or requested this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, default='', help_text='Celery task ID if dispatched asynchronously.', max_length=100)),
                ('started_at', models.DateTimeField(blank=True, help_text='When generation started.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When generation completed.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Job status.', max_length=20)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error if generation failed.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='reports.report')),
            ],
            options={
                'verbose_name': 'report generation job',
                'verbose_name_plural': 'report generation jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='What this template produces.')),
                ('report_type', models.CharField(choices=[('weather', 'Weather Report'), ('farm', 'Farm Report'), ('crop_cycle', 'Crop Cycle Report'), ('yield', 'Yield Report'), ('recommendation', 'Recommendation Report'), ('officer', 'Agricultural Officer Report'), ('system', 'System Report'), ('farmer', 'Farmer Report'), ('crop', 'Crop Report'), ('production', 'Production Report'), ('administrative', 'Administrative Report')], help_text='Report type this template is for.', max_length=20)),
                ('parameters_schema', models.JSONField(default=dict, help_text='JSON schema describing expected parameters (filters, options).')),
                ('template_content', models.TextField(blank=True, default='', help_text='Template body (e.g. HTML template, markdown template, query reference).')),
                ('default_access_level', models.CharField(choices=[('owner_only', 'Owner Only'), ('owner_and_officers', 'Owner + Assigned Officers'), ('owner_and_admin', 'Owner + Admins'), ('all_officers', 'All Agricultural Officers'), ('all_users', 'All Authenticated Users'), ('public', 'Public (no auth)')], default='owner_only', help_text='Default access level for reports using this template.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report template',
                'verbose_name_plural': 'report templates',
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status', 'created_at'], name='reports_rep_report__c2114a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['farm', 'report_type'], name='reports_rep_farm_id_1827ec_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by', 'created_at'], name='reports_rep_generat_b60f00_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'created_at'], name='reports_rep_status_22ec20_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['access_level', 'report_type'], name='reports_rep_access__9954b2_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['filter_period_start', 'filter_period_end'], name='reports_rep_filter__93e442_idx'),
        ),
    ]
