# Generated by Django 6.1.1 on 2026-09-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('weather_alert', 'Weather Alert'), ('crop_stage_reminder', 'Crop Stage Reminder'), ('recommendation_update', 'Recommendation Update'), ('report_ready', 'Report Ready'), ('system_announcement', 'System Announcement'), ('yield_alert', 'Yield Alert'), ('custom', 'Custom')], help_text='Category of notification.', max_length=30)),
                ('title', models.CharField(help_text='Notification title / subject.', max_length=255)),
                ('body', models.TextField(help_text='Notification body / message content.')),
                ('data', models.JSONField(blank=True, help_text='Additional data for the notification (e.g. farm id, link).', null=True)),
                ('delivery_methods', models.JSONField(default=list, help_text="List of delivery methods attempted (e.g. ['in_app', 'native']).")),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the notification was delivered (all methods).', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user read the notification.', null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification.')),
                ('is_deliverable', models.BooleanField(default=True, help_text='Whether the notification should be delivered (false to suppress).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('in_app', 'In-App'), ('native', 'Native (Tauri/Desktop)'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push (Mobile)')], help_text='Delivery method used.', max_length=20)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='When the delivery was attempted.')),
                ('succeeded', models.BooleanField(default=False, help_text='Whether the delivery succeeded.')),
                ('response_info', models.JSONField(blank=True, help_text='Provider response info (e.g. email ID, error details).', null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'notification delivery log',
                'verbose_name_plural': 'notification delivery logs',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_types_in_app', models.JSONField(default=list, help_text="Notification types delivered via in-app (e.g. ['weather_alert', 'crop_stage_reminder']).")),
                ('enabled_types_native', models.JSONField(default=list, help_text='Notification types delivered via native desktop notification.')),
                ('enabled_types_email', models.JSONField(default=list, help_text='Notification types delivered via email.')),
                ('enable_in_app', models.BooleanField(default=True)),
                ('enable_native', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=False)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_push', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Quiet hours start (local time). Notifications suppressed during this window.', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Quiet hours end (local time).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'),
        ),
    ]
