# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('cycles', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('weather_suitability', 'Weather Suitability'), ('crop_suitability', 'Crop Suitability'), ('yield_estimate', 'Yield Estimate'), ('recommendation', 'Recommendation')], help_text='Type of intelligence result.', max_length=30)),
                ('data_classification', models.CharField(help_text='observed | calculated | predicted | recommended', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Suitability score (0-100) or confidence score.', max_digits=6, null=True)),
                ('value', models.JSONField(blank=True, help_text='Result value (e.g. yield estimate, action text).', null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, help_text='Confidence in the result (0.000-1.000).', max_digits=4, null=True)),
                ('factors', models.JSONField(blank=True, help_text='Factors that contributed to the result.', null=True)),
                ('explanation', models.TextField(blank=True, default='', help_text='Human-readable explanation of how the result was generated.')),
                ('model_name', models.CharField(blank=True, default='', help_text="Name of the model or algorithm used (e.g. 'baseline_yield').", max_length=50)),
                ('input_data_snapshot', models.JSONField(blank=True, help_text='Snapshot of input data used to generate the result.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, help_text='Crop this result relates to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_results', to='crops.crop')),
                ('crop_cycle', models.ForeignKey(blank=True, help_text='Crop cycle this result relates to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_results', to='cycles.cropcycle')),
                ('farm', models.ForeignKey(help_text='Farm this result applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_results', to='farms.farm')),
                ('generated_by', models.ForeignKey(blank=True, help_text='User or system that generated this result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_intelligence', to=settings.AUTH_USER_MODEL)),
                ('variety', models.ForeignKey(blank=True, help_text='Variety this result relates to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_results', to='crops.variety')),
            ],
            options={
                'verbose_name': 'intelligence result',
                'verbose_name_plural': 'intelligence results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm', 'result_type', 'created_at'], name='intelligenc_farm_id_6c243e_idx'), models.Index(fields=['crop', 'result_type', 'created_at'], name='intelligenc_crop_id_4ce9f7_idx'), models.Index(fields=['data_classification'], name='intelligenc_data_cl_cc713e_idx'), models.Index(fields=['confidence'], name='intelligenc_confide_57a3ac_idx')],
            },
        ),
    ]
