# Generated by Django 6.1.1 on 2026-09-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Setting key (e.g. 'yield_baseline_confidence_default').", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable setting name.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='What this setting controls.')),
                ('category', models.CharField(choices=[('yield_model', 'Yield Model'), ('suitability', 'Suitability'), ('recommendation', 'Recommendation'), ('weather', 'Weather'), ('notification', 'Notification'), ('farm', 'Farm'), ('crop', 'Crop'), ('system', 'System'), ('user_interface', 'User Interface')], default='system', help_text='Category for organization and filtering.', max_length=30)),
                ('value_type', models.CharField(help_text='Data type of the value: string, integer, float, boolean, json.', max_length=20)),
                ('value', models.JSONField(help_text='Current setting value.')),
                ('default_value', models.JSONField(blank=True, help_text='Default value if not explicitly set.', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this setting is visible to non-admin users.')),
                ('is_dynamic', models.BooleanField(default=False, help_text='Whether this setting can be changed at runtime without restart.')),
                ('requires_restart', models.BooleanField(default=False, help_text='Whether changing this setting requires a service restart.')),
                ('set_at', models.DateTimeField(auto_now_add=True, help_text='When this value was last set.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system setting',
                'verbose_name_plural': 'system settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
