# Generated by Django 6.1.1 on 2026-09-09 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login_failure', 'Login Failure'), ('password_change', 'Password Change'), ('permission_denied', 'Permission Denied'), ('system', 'System Operation')], help_text='Type of action performed.', max_length=20)),
                ('action_object_type', models.CharField(help_text="Type of object affected (e.g. 'farm', 'user', 'crop_cycle').", max_length=50)),
                ('action_object_id', models.PositiveIntegerField(help_text='ID of the object affected.')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable description of the action.')),
                ('old_values', models.JSONField(blank=True, help_text='Snapshot of values before the change (for updates/deletes).', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Snapshot of values after the change (for creates/updates).', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address when available.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Client user agent when available.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (nullable for system actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_6a26ed_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_d8a8b1_idx'), models.Index(fields=['action_object_type', 'action_object_id'], name='audit_audit_action__b4accd_idx')],
            },
        ),
    ]
