# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
from django.db import migrations, models
from ayis.base.geo_compat import geo_models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable source name.', max_length=100, unique=True)),
                ('provider', models.CharField(help_text="Provider identifier (e.g. 'open-meteo', 'nasa-power').", max_length=50)),
                ('api_endpoint', models.URLField(blank=True, default='', help_text='API endpoint URL if applicable.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is currently active.')),
                ('priority', models.SmallIntegerField(default=10, help_text='Priority for data ingestion (lower = higher priority).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'weather source',
                'verbose_name_plural': 'weather sources',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the sync job started.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the sync job completed (null if still running).', null=True)),
                ('status', models.CharField(default='pending', help_text='Job status: pending, running, completed, failed.', max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0, help_text='Number of weather records processed.')),
                ('records_created', models.PositiveIntegerField(default=0, help_text='Number of new observations created.')),
                ('records_updated', models.PositiveIntegerField(default=0, help_text='Number of existing observations updated.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if the job failed.')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='weather.weathersource')),
            ],
            options={
                'verbose_name': 'weather sync job',
                'verbose_name_plural': 'weather sync jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, help_text='Timestamp of the observation.')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the observation location.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the observation location.', max_digits=9)),
                ('location', geo_models.PointField(blank=True, help_text='PostGIS point for spatial queries.', null=True, srid=4326)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, help_text='Temperature in Celsius.', max_digits=5, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, help_text='Rainfall in mm (for the observation period).', max_digits=8, null=True)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Relative humidity percentage.', max_digits=5, null=True)),
                ('wind_speed_ms', models.DecimalField(blank=True, decimal_places=2, help_text='Wind speed in meters per second.', max_digits=6, null=True)),
                ('pressure_hpa', models.DecimalField(blank=True, decimal_places=2, help_text='Atmospheric pressure in hPa.', max_digits=7, null=True)),
                ('data_quality', models.CharField(default='unknown', help_text='Data quality indicator: good, fair, poor, no_data, forecast.', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, help_text='Original API response payload for provenance.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(help_text='Weather source that provided this observation.', on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='weather.weathersource')),
            ],
            options={
                'verbose_name': 'weather observation',
                'verbose_name_plural': 'weather observations',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['observed_at'], name='weather_wea_observe_606f9c_idx'), models.Index(fields=['latitude', 'longitude', 'observed_at'], name='weather_wea_latitud_f65fc6_idx'), models.Index(fields=['source', 'observed_at'], name='weather_wea_source__d24135_idx')],
                'unique_together': {('source', 'observed_at', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_at', models.DateTimeField(db_index=True, help_text='Timestamp when the forecast was issued.')),
                ('forecast_for', models.DateTimeField(db_index=True, help_text='Timestamp the forecast is for.')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the forecast location.', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the forecast location.', max_digits=9)),
                ('location', geo_models.PointField(blank=True, help_text='PostGIS point for spatial queries.', null=True, srid=4326)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall_probability', models.DecimalField(blank=True, decimal_places=2, help_text='Probability of precipitation (0-100%).', max_digits=5, null=True)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed_ms', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weather_code', models.CharField(blank=True, default='', help_text='Weather condition code from the source.', max_length=10)),
                ('data_quality', models.CharField(default='forecast', help_text='Data quality indicator.', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(help_text='Weather source that provided this forecast.', on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='weather.weathersource')),
            ],
            options={
                'verbose_name': 'weather forecast',
                'verbose_name_plural': 'weather forecasts',
                'ordering': ['forecast_for'],
                'indexes': [models.Index(fields=['forecast_for'], name='weather_wea_forecas_5190bf_idx'), models.Index(fields=['latitude', 'longitude', 'forecast_for'], name='weather_wea_latitud_0ab14e_idx')],
            },
        ),
    ]
