"""
AYIS notifications models and data access.

Notifications are generated by the system and delivered to users via:
- In-app notification center
- Tauri native notifications (desktop)
- Future: email, SMS, push (mobile)

Notification types:
- Weather alerts (extremes, thresholds)
- Crop cycle stage reminders
- Recommendation updates
- Report ready
- System announcements
"""

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Notification(models.Model):
    """
    A notification to be delivered to a user.

    Read/unread tracking, delivery status, and type categorization.
    """

    class NotificationType(models.TextChoices):
        WEATHER_ALERT = "weather_alert", "Weather Alert"
        CROP_STAGE_REMINDER = "crop_stage_reminder", "Crop Stage Reminder"
        RECOMMENDATION_UPDATE = "recommendation_update", "Recommendation Update"
        REPORT_READY = "report_ready", "Report Ready"
        SYSTEM_ANNOUNCEMENT = "system_announcement", "System Announcement"
        YIELD_ALERT = "yield_alert", "Yield Alert"
        CUSTOM = "custom", "Custom"

    class DeliveryMethod(models.TextChoices):
        IN_APP = "in_app", "In-App"
        NATIVE = "native", "Native (Tauri/Desktop)"
        EMAIL = "email", "Email"
        SMS = "sms", "SMS"
        PUSH = "push", "Push (Mobile)"

    recipient = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="notifications",
        help_text="User who receives this notification.",
    )

    notification_type = models.CharField(
        max_length=30,
        choices=NotificationType.choices,
        help_text="Category of notification.",
    )

    title = models.CharField(
        max_length=255,
        help_text="Notification title / subject.",
    )

    body = models.TextField(
        help_text="Notification body / message content.",
    )

    data = models.JSONField(
        null=True,
        blank=True,
        help_text="Additional data for the notification (e.g. farm id, link).",
    )

    # Delivery tracking
    delivery_methods = models.JSONField(
        default=list,
        help_text="List of delivery methods attempted (e.g. ['in_app', 'native']).",
    )

    delivered_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the notification was delivered (all methods).",
    )

    read_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the user read the notification.",
    )

    is_read = models.BooleanField(
        default=False,
        help_text="Whether the user has read this notification.",
    )

    is_deliverable = models.BooleanField(
        default=True,
        help_text="Whether the notification should be delivered (false to suppress).",
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "notification"
        verbose_name_plural = "notifications"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["recipient", "-created_at"]),
            models.Index(fields=["recipient", "is_read"]),
            models.Index(fields=["notification_type", "-created_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.notification_type}: {self.title} → {self.recipient.username}"


class NotificationPreference(models.Model):
    """
    Per-user notification delivery preferences.

    Controls which notification types are delivered via which channels.
    """

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="notification_preferences",
    )

    # Type-level preferences: which types are enabled per channel
    enabled_types_in_app = models.JSONField(
        default=list,
        help_text="Notification types delivered via in-app (e.g. ['weather_alert', 'crop_stage_reminder']).",
    )

    enabled_types_native = models.JSONField(
        default=list,
        help_text="Notification types delivered via native desktop notification.",
    )

    enabled_types_email = models.JSONField(
        default=list,
        help_text="Notification types delivered via email.",
    )

    # Global toggles
    enable_in_app = models.BooleanField(default=True)
    enable_native = models.BooleanField(default=True)
    enable_email = models.BooleanField(default=False)
    enable_sms = models.BooleanField(default=False)
    enable_push = models.BooleanField(default=False)

    # Quiet hours (optional)
    quiet_hours_start = models.TimeField(
        null=True,
        blank=True,
        help_text="Quiet hours start (local time). Notifications suppressed during this window.",
    )

    quiet_hours_end = models.TimeField(
        null=True,
        blank=True,
        help_text="Quiet hours end (local time).",
    )

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "notification preference"
        verbose_name_plural = "notification preferences"

    def __str__(self) -> str:
        return f"Notification preferences for {self.user.username}"


class NotificationDeliveryLog(models.Model):
    """
    Log of notification delivery attempts.

    Tracks which delivery methods were attempted, when, and whether they succeeded.
    """

    notification = models.ForeignKey(
        Notification,
        on_delete=models.CASCADE,
        related_name="delivery_logs",
    )

    method = models.CharField(
        max_length=20,
        choices=Notification.DeliveryMethod.choices,
        help_text="Delivery method used.",
    )

    attempted_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When the delivery was attempted.",
    )

    succeeded = models.BooleanField(
        default=False,
        help_text="Whether the delivery succeeded.",
    )

    response_info = models.JSONField(
        null=True,
        blank=True,
        help_text="Provider response info (e.g. email ID, error details).",
    )

    class Meta:
        verbose_name = "notification delivery log"
        verbose_name_plural = "notification delivery logs"
        ordering = ["-attempted_at"]

    def __str__(self) -> str:
        return f"{self.method} delivery for {self.notification.title} — {'OK' if self.succeeded else 'FAIL'}"


class NotificationService:
    """
    Stateless service for notification operations.

    Creates notifications, manages preferences, and triggers delivery.
    """

    @staticmethod
    def create_notification(
        recipient: User,
        notification_type: str,
        title: str,
        body: str,
        data: dict | None = None,
        delivery_methods: list[str] | None = None,
    ) -> Notification:
        """Create a notification for a user."""
        return Notification.objects.create(
            recipient=recipient,
            notification_type=notification_type,
            title=title,
            body=body,
            data=data,
            delivery_methods=delivery_methods or ["in_app"],
        )

    @staticmethod
    def mark_read(notification: Notification) -> None:
        """Mark a notification as read."""
        notification.is_read = True
        notification.read_at = models.functions.Now()
        notification.save()

    @staticmethod
    def mark_all_read(user: User) -> int:
        """Mark all unread notifications for a user as read. Returns count."""
        return Notification.objects.filter(
            recipient=user, is_read=False
        ).update(is_read=True, read_at=models.functions.Now())

    @staticmethod
    def get_unread_count(user: User) -> int:
        """Get the count of unread notifications for a user."""
        return Notification.objects.filter(recipient=user, is_read=False).count()

    @staticmethod
    def get_unread_notifications(user: User, limit: int = 50):
        """Get unread notifications for a user, newest first."""
        return Notification.objects.filter(
            recipient=user, is_read=False
        ).order_by("-created_at")[:limit]

    @staticmethod
    def get_notifications(user: User, limit: int = 100, offset: int = 0):
        """Get notifications for a user with pagination."""
        return Notification.objects.filter(
            recipient=user
        ).order_by("-created_at")[offset:offset + limit]

    @staticmethod
    def get_preferences(user: User):
        """Get or create notification preferences for a user."""
        pref, _ = NotificationPreference.objects.get_or_create(user=user)
        return pref

    @staticmethod
    def set_preferences(user: User, **updates) -> NotificationPreference:
        """Update notification preferences for a user."""
        pref, _ = NotificationPreference.objects.get_or_create(user=user)
        for key, value in updates.items():
            if hasattr(pref, key):
                setattr(pref, key, value)
        pref.save()
        return pref


notification_service = NotificationService()
