# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cycles', '0001_initial'),
        ('intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField(help_text='Date of harvest.')),
                ('production_area_ha', models.DecimalField(blank=True, decimal_places=3, help_text='Area harvested in this record (ha).', max_digits=10, null=True)),
                ('quantity_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity harvested (kg).', max_digits=12, null=True)),
                ('actual_yield_kg_ha', models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield calculated as quantity / area (kg/ha).', max_digits=10, null=True)),
                ('quality_grade', models.CharField(blank=True, default='', help_text="Quality grade (e.g. 'A', 'B', 'standard').", max_length=20)),
                ('quality_notes', models.TextField(blank=True, default='', help_text='Notes on quality.')),
                ('sale_price_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Sale price per kg (currency units).', max_digits=10, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Total revenue from this harvest (currency units).', max_digits=12, null=True)),
                ('storage_used', models.CharField(blank=True, default='', help_text="Storage type used (e.g. 'silo', 'bag', 'cold storage').", max_length=50)),
                ('storage_loss_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Storage loss percentage.', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='General notes about this harvest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(help_text='Crop cycle this harvest belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='cycles.cropcycle')),
                ('predicted_intelligence', models.ForeignKey(blank=True, help_text='The intelligence result (yield estimate) this harvest validates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_by_harvests', to='intelligence.intelligenceresult')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_harvests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'harvest',
                'verbose_name_plural': 'harvests',
                'ordering': ['-harvest_date'],
                'indexes': [models.Index(fields=['cycle', 'harvest_date'], name='production__cycle_i_4f10b5_idx'), models.Index(fields=['actual_yield_kg_ha'], name='production__actual__081ed6_idx')],
            },
        ),
    ]
