# Generated by Django 6.1.1 on 2026-09-09 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(blank=True, help_text='Date the crop was planted.', null=True)),
                ('expected_harvest_date', models.DateField(blank=True, help_text='Expected harvest date (calculated or entered).', null=True)),
                ('actual_harvest_date', models.DateField(blank=True, help_text='Actual harvest date (filled after harvest).', null=True)),
                ('current_stage', models.CharField(choices=[('not_planted', 'Not Planted'), ('planted', 'Planted'), ('germinated', 'Germinated'), ('vegetative', 'Vegetative Growth'), ('reproductive', 'Reproductive Stage'), ('harvest_ready', 'Harvest Ready'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='not_planted', help_text='Current growth stage.', max_length=20)),
                ('stage_updated_at', models.DateTimeField(blank=True, help_text='When the current stage was last updated.', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', help_text='Overall cycle status.', max_length=20)),
                ('area_ha', models.DecimalField(blank=True, decimal_places=3, help_text='Area planted in this cycle (ha).', max_digits=10, null=True)),
                ('plant_density_plants_per_ha', models.PositiveIntegerField(blank=True, help_text='Planting density (plants per hectare).', null=True)),
                ('seeds_used_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Amount of seed used (kg).', max_digits=8, null=True)),
                ('seeds_used_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of seeds used (currency units).', max_digits=10, null=True)),
                ('fertilizer_nitrogen_kg', models.DecimalField(decimal_places=3, default=0, help_text='Total nitrogen applied (kg).', max_digits=8)),
                ('fertilizer_phosphorus_kg', models.DecimalField(decimal_places=3, default=0, help_text='Total phosphorus applied (kg).', max_digits=8)),
                ('fertilizer_potassium_kg', models.DecimalField(decimal_places=3, default=0, help_text='Total potassium applied (kg).', max_digits=8)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total fertilizer cost (currency units).', max_digits=10)),
                ('irrigation_events', models.PositiveIntegerField(default=0, help_text='Number of irrigation events.')),
                ('irrigation_water_total_liters', models.PositiveIntegerField(default=0, help_text='Total irrigation water used (liters).')),
                ('irrigation_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total irrigation cost (currency units).', max_digits=10)),
                ('pesticide_applications', models.PositiveIntegerField(default=0, help_text='Number of pesticide applications.')),
                ('pesticide_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total pesticide cost (currency units).', max_digits=10)),
                ('disease_incidents', models.PositiveIntegerField(default=0, help_text='Number of disease incidents recorded.')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total labor hours spent on this cycle.', max_digits=8)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total labor cost (currency units).', max_digits=10)),
                ('notes', models.TextField(blank=True, default='', help_text='General notes about this cycle.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cycles', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(help_text='Crop being grown.', on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='crops.crop')),
                ('farm', models.ForeignKey(help_text='Farm where this cycle is grown.', on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='farms.farm')),
                ('variety', models.ForeignKey(blank=True, help_text='Specific variety planted (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles', to='crops.variety')),
            ],
            options={
                'verbose_name': 'crop cycle',
                'verbose_name_plural': 'crop cycles',
                'ordering': ['-planting_date'],
                'indexes': [models.Index(fields=['farm', 'status'], name='cycles_crop_farm_id_b71fbc_idx'), models.Index(fields=['farm', 'crop', 'planting_date'], name='cycles_crop_farm_id_3100c2_idx'), models.Index(fields=['status', 'current_stage'], name='cycles_crop_status_5fef94_idx'), models.Index(fields=['expected_harvest_date'], name='cycles_crop_expecte_0e10d1_idx')],
            },
        ),
    ]
