import {
  User,
  Farm,
  Field,
  Crop,
  CropProfile,
  CropCycle,
  WeatherRecord,
  WeatherForecast,
  WeatherSuitability,
  YieldEstimate,
  Recommendation,
  WeatherAlert,
  FieldObservation,
  Inspection,
  Report,
  Notification,
  FieldVisit,
  FollowUpTask,
  WeatherStation,
  DataQualityMetric,
  WeatherTrendPoint,
  AuditLog,
  SystemServiceHealth,
  WeatherSourceConfig,
  SystemSettings,
} from '@/lib/types'

// Mock Data Sets (Simulating Django REST API Backend Store)
export const MOCK_USERS: User[] = [
  {
    id: 1,
    username: 'admin_joseph',
    email: 'joseph@agriculture.gov.ke',
    first_name: 'Joseph',
    last_name: 'Kariuki',
    role: 'admin',
    is_active: true,
    is_staff: true,
    organization: 'Ministry of Agriculture',
    date_joined: '2025-01-10T08:00:00Z',
  },
  {
    id: 2,
    username: 'agronomist_sarah',
    email: 'sarah.mwangi@agri-intel.org',
    first_name: 'Sarah',
    last_name: 'Mwangi',
    role: 'agronomist',
    is_active: true,
    is_staff: false,
    organization: 'Agronomy Research Center',
    date_joined: '2025-02-15T09:30:00Z',
  },
  {
    id: 3,
    username: 'farmer_otieno',
    email: 'otieno.farms@gmail.com',
    first_name: 'Peter',
    last_name: 'Otieno',
    role: 'farmer',
    is_active: true,
    is_staff: false,
    phone_number: '+254 712 345 678',
    organization: 'Rift Valley Smallholders Cooperative',
    date_joined: '2025-03-01T11:00:00Z',
  },
  {
    id: 4,
    username: 'farmer_mary',
    email: 'mary.wanjiku@kenyagri.co.ke',
    first_name: 'Mary',
    last_name: 'Wanjiku',
    role: 'farmer',
    is_active: true,
    is_staff: false,
    phone_number: '+254 722 890 123',
    organization: 'Mau Highland Horticultural Growers',
    date_joined: '2025-02-20T10:00:00Z',
  },
  {
    id: 5,
    username: 'farmer_kiprono',
    email: 'kiprono.chem@gmail.com',
    first_name: 'David',
    last_name: 'Kiprono',
    role: 'farmer',
    is_active: true,
    is_staff: false,
    phone_number: '+254 733 456 789',
    organization: 'Trans-Nzoia Grain Producers Union',
    date_joined: '2025-01-25T14:15:00Z',
  },
  {
    id: 6,
    username: 'officer_brian',
    email: 'brian.omondi@agriculture.gov.ke',
    first_name: 'Brian',
    last_name: 'Omondi',
    role: 'extension_officer',
    is_active: true,
    is_staff: true,
    phone_number: '+254 711 223 344',
    organization: 'Rift Valley Agricultural Extension Service',
    date_joined: '2024-10-01T08:00:00Z',
  },
]

export const MOCK_FARMS: Farm[] = [
  {
    id: 1,
    owner: 3,
    owner_username: 'farmer_otieno',
    name: 'Green Ridge Highland Estate',
    location_name: 'Nakuru County, Rift Valley',
    longitude: 36.080026,
    latitude: -0.303099,
    area_ha: 42.5,
    soil_type: 'Volcanic loam',
    climate_zone: 'Sub-humid highland',
    notes: 'Primary hub for certified seed potato and high-grade highland maize production.',
    data_classification: 'INTERNAL',
    created_at: '2025-01-12T10:00:00Z',
    updated_at: '2025-09-01T14:30:00Z',
  },
  {
    id: 2,
    owner: 3,
    owner_username: 'farmer_otieno',
    name: 'Mau Escarpment Terraces',
    location_name: 'Narok North',
    longitude: 35.871142,
    latitude: -0.687231,
    area_ha: 18.0,
    soil_type: 'Clay loam',
    climate_zone: 'Temperate highland',
    notes: 'Terraced agro-ecological fields focusing on wheat rotation and legume trials.',
    data_classification: 'INTERNAL',
    created_at: '2025-02-04T08:20:00Z',
    updated_at: '2025-08-20T16:00:00Z',
  },
  {
    id: 3,
    owner: 1,
    owner_username: 'admin_joseph',
    name: 'Kitale National Demonstration Farm',
    location_name: 'Trans-Nzoia County',
    longitude: 35.006248,
    latitude: 1.015723,
    area_ha: 120.0,
    soil_type: 'Deep red volcanic clay',
    climate_zone: 'Highland wet',
    notes: 'Government trial and research block for drought-tolerant maize cultivars.',
    data_classification: 'PUBLIC',
    created_at: '2024-11-10T09:00:00Z',
    updated_at: '2025-09-10T12:00:00Z',
  },
]

export const MOCK_FIELDS: Field[] = [
  {
    id: 101,
    farm_id: 1,
    name: 'North Terrace Block A',
    area_ha: 14.5,
    soil_ph: 6.4,
    soil_organic_matter: 3.8,
    irrigation_type: 'drip',
    status: 'active',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 102,
    farm_id: 1,
    name: 'Valley Bottom Block B',
    area_ha: 28.0,
    soil_ph: 5.9,
    soil_organic_matter: 4.1,
    irrigation_type: 'sprinkler',
    status: 'active',
    created_at: '2025-01-15T09:30:00Z',
  },
  {
    id: 201,
    farm_id: 2,
    name: 'Ridge Plot 1',
    area_ha: 18.0,
    soil_ph: 6.8,
    soil_organic_matter: 3.2,
    irrigation_type: 'rainfed',
    status: 'active',
    created_at: '2025-02-10T10:00:00Z',
  },
]

export const MOCK_CROPS: Crop[] = [
  {
    id: 1,
    name: 'White Maize (H6213)',
    scientific_name: 'Zea mays',
    category: 'cereal',
    description: 'Late-maturing highland hybrid with high yield potential and blight tolerance.',
    growing_days_typical: 165,
    optimal_temp_min: 18,
    optimal_temp_max: 27,
    rainfall_optimum_mm: 750,
    expected_yield_typical_kg_ha: 5500,
    planting_season: 'Long Rains (March - April)',
    harvest_season: 'August - September',
    is_active: true,
  },
  {
    id: 2,
    name: 'Shangi Potato',
    scientific_name: 'Solanum tuberosum',
    category: 'tuber',
    description: 'Early-maturing Dutch variety widely adapted for quick cash turnaround in highland soils.',
    growing_days_typical: 95,
    optimal_temp_min: 15,
    optimal_temp_max: 22,
    rainfall_optimum_mm: 500,
    expected_yield_typical_kg_ha: 18000,
    planting_season: 'Short & Long Rains',
    harvest_season: 'June / December',
    is_active: true,
  },
  {
    id: 3,
    name: 'French Beans (Serengeti)',
    scientific_name: 'Phaseolus vulgaris',
    category: 'vegetable',
    description: 'Premium export pod variety with uniform length and high resistance to rust.',
    growing_days_typical: 60,
    optimal_temp_min: 20,
    optimal_temp_max: 28,
    rainfall_optimum_mm: 400,
    expected_yield_typical_kg_ha: 8500,
    planting_season: 'Year-round under irrigation',
    harvest_season: 'Continuous',
    is_active: true,
  },
]

export const MOCK_CYCLES: CropCycle[] = [
  {
    id: 1,
    farm: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 101,
    field_name: 'North Terrace Block A',
    crop: 1,
    crop_name: 'White Maize (H6213)',
    variety_name: 'Highland Hybrid H6213',
    planting_date: '2025-03-20',
    expected_harvest_date: '2025-09-15',
    current_stage: 'flowering',
    status: 'active',
    area_ha: 14.5,
    target_yield_kg_ha: 5600,
    actual_yield_kg_ha: undefined,
    notes: 'Second top-dressing completed; tassel emergence looking exceptionally uniform.',
  },
  {
    id: 2,
    farm: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 102,
    field_name: 'Valley Bottom Block B',
    crop: 2,
    crop_name: 'Shangi Potato',
    variety_name: 'Certified Clean Seed G2',
    planting_date: '2025-05-10',
    expected_harvest_date: '2025-08-25',
    actual_harvest_date: '2025-08-28',
    current_stage: 'harvested',
    status: 'completed',
    area_ha: 28.0,
    target_yield_kg_ha: 18500,
    actual_yield_kg_ha: 19200,
    notes: 'Exceeded expected yield by 3.7% due to timely drip-fed potassium supplementation.',
  },
  {
    id: 3,
    farm: 2,
    farm_name: 'Mau Escarpment Terraces',
    field_id: 201,
    field_name: 'Ridge Plot 1',
    crop: 3,
    crop_name: 'French Beans (Serengeti)',
    variety_name: 'Export Grade Extra-Fine',
    planting_date: '2025-08-01',
    expected_harvest_date: '2025-10-05',
    current_stage: 'vegetative',
    status: 'active',
    area_ha: 18.0,
    target_yield_kg_ha: 8000,
    notes: 'First preventive spray against whitefly completed.',
  },
]

export const MOCK_WEATHER_STATIONS: WeatherStation[] = [
  {
    id: 'WS-NAK-01',
    name: 'Nakuru High Ridge Micro-Station',
    location_name: 'Nakuru North (Rift Valley)',
    county: 'Nakuru',
    latitude: -0.303099,
    longitude: 36.080026,
    elevation_m: 1980,
    hardware_model: 'Davis Vantage Pro2 Plus / Campbell CR1000X',
    operational_status: 'online',
    last_transmission: '2026-09-11T14:15:00Z',
    battery_pct: 98,
    solar_voltage_v: 14.2,
    signal_strength_dbm: -68,
    completeness_24h_pct: 99.6,
    assigned_farms: ['Green Ridge Highland Estate', 'Menengai Caldera Agro-forestry'],
  },
  {
    id: 'WS-NAR-02',
    name: 'Mau Escarpment Automated Ag-Station',
    location_name: 'Narok North Terraces',
    county: 'Narok',
    latitude: -0.687231,
    longitude: 35.871142,
    elevation_m: 2340,
    hardware_model: 'Vaisala AWS310 Agro Met Suite',
    operational_status: 'online',
    last_transmission: '2026-09-11T14:12:00Z',
    battery_pct: 94,
    solar_voltage_v: 13.9,
    signal_strength_dbm: -74,
    completeness_24h_pct: 98.9,
    assigned_farms: ['Mau Escarpment Terraces', 'Olokurto Smallholder Cereal Cluster'],
  },
  {
    id: 'WS-KIT-03',
    name: 'Trans-Nzoia Demonstration Gauge',
    location_name: 'Kitale Central Demo Farm',
    county: 'Trans-Nzoia',
    latitude: 1.016667,
    longitude: 35.000000,
    elevation_m: 1890,
    hardware_model: 'Metos Pessl iMETOS 3.3',
    operational_status: 'delayed',
    last_transmission: '2026-09-11T12:45:00Z',
    battery_pct: 76,
    solar_voltage_v: 12.1,
    signal_strength_dbm: -88,
    completeness_24h_pct: 91.2,
    assigned_farms: ['Kitale National Demonstration Farm'],
  },
  {
    id: 'WS-ELD-04',
    name: 'Uasin Gishu Highland Plateau Sensor',
    location_name: 'Eldoret South Maize Belt',
    county: 'Uasin Gishu',
    latitude: 0.514277,
    longitude: 35.269779,
    elevation_m: 2090,
    hardware_model: 'Campbell Scientific MetNet Pro',
    operational_status: 'online',
    last_transmission: '2026-09-11T14:16:30Z',
    battery_pct: 99,
    solar_voltage_v: 14.4,
    signal_strength_dbm: -62,
    completeness_24h_pct: 100.0,
    assigned_farms: ['Plateau Seed Producers', 'Sergoit Agro-Hub'],
  },
  {
    id: 'WS-KER-05',
    name: 'Kericho Highland Tea & Agro-Forestry Station',
    location_name: 'Mau Forest Fringe, Kericho',
    county: 'Kericho',
    latitude: -0.367744,
    longitude: 35.283142,
    elevation_m: 2180,
    hardware_model: 'Davis Vantage Pro2 Wireless',
    operational_status: 'degraded',
    last_transmission: '2026-09-11T13:50:00Z',
    battery_pct: 82,
    solar_voltage_v: 12.8,
    signal_strength_dbm: -82,
    completeness_24h_pct: 87.5,
    assigned_farms: ['Mau Forest Buffer Cooperative', 'Kipkelion Coffee & Maize Zone'],
  },
]

export const MOCK_WEATHER_RECORDS: WeatherRecord[] = [
  {
    id: 1,
    farm_id: 1,
    station_id: 'WS-NAK-01',
    station_name: 'Nakuru High Ridge Micro-Station',
    observed_at: '2026-09-11T14:15:00Z',
    temperature_celsius: 21.4,
    relative_humidity_percent: 68,
    rainfall_mm: 3.8,
    wind_speed_ms: 3.4,
    wind_direction_deg: 140,
    pressure_hpa: 1014.2,
    solar_radiation_mj_m2: 22.8,
    dew_point_c: 14.8,
    soil_temperature_c: 19.2,
    soil_moisture_pct: 34.6,
    data_quality: 'verified',
    latitude: -0.303099,
    longitude: 36.080026,
    source_type: 'telemetry_station',
  },
  {
    id: 2,
    farm_id: 2,
    station_id: 'WS-NAR-02',
    station_name: 'Mau Escarpment Automated Ag-Station',
    observed_at: '2026-09-11T14:12:00Z',
    temperature_celsius: 17.6,
    relative_humidity_percent: 82,
    rainfall_mm: 8.4,
    wind_speed_ms: 4.6,
    wind_direction_deg: 210,
    pressure_hpa: 1011.8,
    solar_radiation_mj_m2: 15.4,
    dew_point_c: 14.2,
    soil_temperature_c: 16.8,
    soil_moisture_pct: 42.1,
    data_quality: 'verified',
    latitude: -0.687231,
    longitude: 35.871142,
    source_type: 'telemetry_station',
  },
  {
    id: 3,
    farm_id: 3,
    station_id: 'WS-KIT-03',
    station_name: 'Trans-Nzoia Demonstration Gauge',
    observed_at: '2026-09-11T12:45:00Z',
    temperature_celsius: 24.2,
    relative_humidity_percent: 59,
    rainfall_mm: 0.0,
    wind_speed_ms: 2.1,
    wind_direction_deg: 90,
    pressure_hpa: 1016.1,
    solar_radiation_mj_m2: 26.1,
    dew_point_c: 15.1,
    soil_temperature_c: 22.4,
    soil_moisture_pct: 28.3,
    data_quality: 'interpolated',
    latitude: 1.016667,
    longitude: 35.000000,
    source_type: 'telemetry_station',
  },
  {
    id: 4,
    station_id: 'WS-ELD-04',
    station_name: 'Uasin Gishu Highland Plateau Sensor',
    observed_at: '2026-09-11T14:16:30Z',
    temperature_celsius: 22.8,
    relative_humidity_percent: 64,
    rainfall_mm: 1.2,
    wind_speed_ms: 3.8,
    wind_direction_deg: 165,
    pressure_hpa: 1013.9,
    solar_radiation_mj_m2: 24.2,
    dew_point_c: 15.4,
    soil_temperature_c: 20.1,
    soil_moisture_pct: 31.9,
    data_quality: 'verified',
    latitude: 0.514277,
    longitude: 35.269779,
    source_type: 'telemetry_station',
  },
  {
    id: 5,
    station_id: 'WS-KER-05',
    station_name: 'Kericho Highland Tea & Agro-Forestry Station',
    observed_at: '2026-09-11T13:50:00Z',
    temperature_celsius: 18.9,
    relative_humidity_percent: 88,
    rainfall_mm: 14.6,
    wind_speed_ms: 2.2,
    wind_direction_deg: 180,
    pressure_hpa: 1012.0,
    solar_radiation_mj_m2: 12.8,
    dew_point_c: 16.7,
    soil_temperature_c: 17.5,
    soil_moisture_pct: 46.2,
    data_quality: 'flagged',
    latitude: -0.367744,
    longitude: 35.283142,
    source_type: 'telemetry_station',
  },
]

export const MOCK_DATA_QUALITY_METRICS: DataQualityMetric[] = [
  {
    station_id: 'WS-NAK-01',
    station_name: 'Nakuru High Ridge Micro-Station',
    last_successful_update: '2026-09-11T14:15:00Z',
    expected_transmissions_24h: 288,
    actual_transmissions_24h: 287,
    missing_data_points: 1,
    delayed_data_points: 2,
    invalid_readings_count: 0,
    completeness_pct: 99.6,
    quality_score: 99.2,
    operational_status: 'healthy',
    data_source_status: 'active_telemetered',
    flagged_sensors: [],
    anomalies_detected: [],
  },
  {
    station_id: 'WS-NAR-02',
    station_name: 'Mau Escarpment Automated Ag-Station',
    last_successful_update: '2026-09-11T14:12:00Z',
    expected_transmissions_24h: 288,
    actual_transmissions_24h: 285,
    missing_data_points: 3,
    delayed_data_points: 4,
    invalid_readings_count: 0,
    completeness_pct: 98.9,
    quality_score: 97.8,
    operational_status: 'healthy',
    data_source_status: 'active_telemetered',
    flagged_sensors: [],
    anomalies_detected: [],
  },
  {
    station_id: 'WS-KIT-03',
    station_name: 'Trans-Nzoia Demonstration Gauge',
    last_successful_update: '2026-09-11T12:45:00Z',
    expected_transmissions_24h: 288,
    actual_transmissions_24h: 262,
    missing_data_points: 26,
    delayed_data_points: 18,
    invalid_readings_count: 2,
    completeness_pct: 91.0,
    quality_score: 86.4,
    operational_status: 'warning',
    data_source_status: 'reanalysis_fallback',
    flagged_sensors: ['pyranometer_drift'],
    anomalies_detected: [
      {
        variable: 'solar_radiation',
        timestamp: '2026-09-11T11:30:00Z',
        reported_value: '1380 W/m²',
        expected_range: '0 - 1150 W/m²',
        severity: 'mild',
      },
    ],
  },
  {
    station_id: 'WS-ELD-04',
    station_name: 'Uasin Gishu Highland Plateau Sensor',
    last_successful_update: '2026-09-11T14:16:30Z',
    expected_transmissions_24h: 288,
    actual_transmissions_24h: 288,
    missing_data_points: 0,
    delayed_data_points: 0,
    invalid_readings_count: 0,
    completeness_pct: 100.0,
    quality_score: 100.0,
    operational_status: 'healthy',
    data_source_status: 'active_telemetered',
    flagged_sensors: [],
    anomalies_detected: [],
  },
  {
    station_id: 'WS-KER-05',
    station_name: 'Kericho Highland Tea & Agro-Forestry Station',
    last_successful_update: '2026-09-11T13:50:00Z',
    expected_transmissions_24h: 288,
    actual_transmissions_24h: 252,
    missing_data_points: 36,
    delayed_data_points: 29,
    invalid_readings_count: 4,
    completeness_pct: 87.5,
    quality_score: 81.2,
    operational_status: 'warning',
    data_source_status: 'active_telemetered',
    flagged_sensors: ['wind_vane_stuck', 'tipping_bucket_chatter'],
    anomalies_detected: [
      {
        variable: 'wind_direction',
        timestamp: '2026-09-11T09:15:00Z',
        reported_value: 'Constant 180.0° for 5h',
        expected_range: 'Angular variance > 12°/hr',
        severity: 'severe',
      },
      {
        variable: 'relative_humidity',
        timestamp: '2026-09-11T10:45:00Z',
        reported_value: '104.2%',
        expected_range: '0 - 100%',
        severity: 'critical',
      },
    ],
  },
]

export const MOCK_WEATHER_TRENDS: WeatherTrendPoint[] = [
  { period: 'May 2026', avg_temp_c: 19.1, min_temp_c: 12.4, max_temp_c: 25.8, cumulative_rainfall_mm: 124.5, normal_rainfall_mm: 110.0, rainfall_anomaly_mm: +14.5, gdd_c: 282, et0_mm: 108.2, humidity_pct: 74, historical_benchmark_temp_c: 18.8 },
  { period: 'Jun 2026', avg_temp_c: 18.2, min_temp_c: 11.2, max_temp_c: 24.5, cumulative_rainfall_mm: 88.2, normal_rainfall_mm: 92.0, rainfall_anomaly_mm: -3.8, gdd_c: 246, et0_mm: 112.5, humidity_pct: 71, historical_benchmark_temp_c: 18.0 },
  { period: 'Jul 2026', avg_temp_c: 17.5, min_temp_c: 10.1, max_temp_c: 23.9, cumulative_rainfall_mm: 64.0, normal_rainfall_mm: 78.0, rainfall_anomaly_mm: -14.0, gdd_c: 232, et0_mm: 118.0, humidity_pct: 69, historical_benchmark_temp_c: 17.4 },
  { period: 'Aug 2026', avg_temp_c: 18.4, min_temp_c: 11.6, max_temp_c: 25.1, cumulative_rainfall_mm: 95.8, normal_rainfall_mm: 85.0, rainfall_anomaly_mm: +10.8, gdd_c: 260, et0_mm: 115.4, humidity_pct: 72, historical_benchmark_temp_c: 18.1 },
  { period: 'Sep 2026 (MTD)', avg_temp_c: 20.2, min_temp_c: 13.0, max_temp_c: 26.7, cumulative_rainfall_mm: 48.6, normal_rainfall_mm: 42.0, rainfall_anomaly_mm: +6.6, gdd_c: 112, et0_mm: 44.8, humidity_pct: 68, historical_benchmark_temp_c: 19.4 },
]

export const MOCK_FORECASTS: WeatherForecast = {
  farm_id: 1,
  generated_at: '2026-09-11T05:00:00Z',
  days: [
    { date: '2026-09-11', temp_min_c: 13, temp_max_c: 24, rainfall_probability_pct: 65, expected_rainfall_mm: 8.5, weather_condition: 'Scattered Showers', weather_code: 80, evapotranspiration_mm: 3.8 },
    { date: '2026-09-12', temp_min_c: 14, temp_max_c: 25, rainfall_probability_pct: 40, expected_rainfall_mm: 2.1, weather_condition: 'Partly Cloudy', weather_code: 2, evapotranspiration_mm: 4.2 },
    { date: '2026-09-13', temp_min_c: 12, temp_max_c: 26, rainfall_probability_pct: 15, expected_rainfall_mm: 0.0, weather_condition: 'Mainly Sunny', weather_code: 1, evapotranspiration_mm: 4.6 },
    { date: '2026-09-14', temp_min_c: 13, temp_max_c: 27, rainfall_probability_pct: 10, expected_rainfall_mm: 0.0, weather_condition: 'Clear Sky', weather_code: 0, evapotranspiration_mm: 4.9 },
    { date: '2026-09-15', temp_min_c: 15, temp_max_c: 25, rainfall_probability_pct: 70, expected_rainfall_mm: 12.0, weather_condition: 'Moderate Rain', weather_code: 63, evapotranspiration_mm: 3.1 },
    { date: '2026-09-16', temp_min_c: 14, temp_max_c: 23, rainfall_probability_pct: 55, expected_rainfall_mm: 5.4, weather_condition: 'Afternoon Showers', weather_code: 80, evapotranspiration_mm: 3.4 },
    { date: '2026-09-17', temp_min_c: 13, temp_max_c: 24, rainfall_probability_pct: 25, expected_rainfall_mm: 0.8, weather_condition: 'Partly Cloudy', weather_code: 2, evapotranspiration_mm: 3.9 },
  ],
}

export const MOCK_WEATHER_ALERTS: WeatherAlert[] = [
  {
    id: 1,
    farm_id: 1,
    station_id: 'WS-NAK-01',
    location: 'Nakuru North Sub-County',
    alert_type: 'heavy_rain',
    severity: 'moderate',
    headline: 'High Rainfall Episode Expected on Sept 15',
    description: 'Convective convergence system likely to deposit >15mm within 3 hours. Potential localized waterlogging in lower slope fields.',
    trigger_condition: 'Precipitation intensity > 5.0 mm/hr forecast for >= 3 continuous hours with convective CAPE > 1400 J/kg',
    status: 'active',
    affected_farms: ['Green Ridge Highland Estate', 'Menengai Caldera Agro-forestry'],
    affected_crops: ['Maize (Flowering stage)', 'French Beans (Vegetative)'],
    effective_from: '2026-09-15T11:00:00Z',
    effective_to: '2026-09-15T20:00:00Z',
    recommended_actions: [
      'Inspect terrace drainage channels on Block B',
      'Delay foliar pesticide applications until after Sept 16',
      'Ensure grain storage facilities are sealed against dampness',
    ],
  },
  {
    id: 2,
    station_id: 'WS-NAR-02',
    location: 'Mau Escarpment High Ridge (Narok)',
    alert_type: 'frost',
    severity: 'high',
    headline: 'Radiational Highland Chilling / Frost Hazard',
    description: 'Catabatic cold air drainage during early morning hours projected to drop surface grass temperatures to 2.8°C.',
    trigger_condition: 'Screen temperature < 4.0°C and 10m wind speed < 1.0 m/s between 02:00 and 06:30 local solar time',
    status: 'active',
    affected_farms: ['Mau Escarpment Terraces', 'Olokurto Valley Holdings'],
    affected_crops: ['French Beans (Export grade)', 'Young Potato Sprouts'],
    effective_from: '2026-09-14T02:30:00Z',
    effective_to: '2026-09-14T07:00:00Z',
    recommended_actions: [
      'Deploy protective micro-sprinklers before 03:00 to release latent heat',
      'Ensure seedling nursery shade nets are drawn shut',
      'Alert legume outgrowers to inspect for leaf necrosis post-sunrise',
    ],
  },
  {
    id: 3,
    station_id: 'WS-KIT-03',
    location: 'Trans-Nzoia Western Grain Belt',
    alert_type: 'high_winds',
    severity: 'medium',
    headline: 'Convective Gust Squalls Exceeding 18 m/s',
    description: 'Approaching squall line from Mount Elgon slopes generating sharp downdrafts and elevated lodging risk.',
    trigger_condition: 'Sustained gust speeds exceeding 15.4 m/s (55 km/h) accompanied by rapid barometric drop > 2.5 hPa/hr',
    status: 'monitoring',
    affected_farms: ['Kitale National Demonstration Farm', 'Endebess Grain Co-op'],
    affected_crops: ['Tall Hybrid Maize (Tassel stage)'],
    effective_from: '2026-09-12T13:00:00Z',
    effective_to: '2026-09-12T18:30:00Z',
    recommended_actions: [
      'Halt high-clearance tractor spray rigs',
      'Secure temporary canopy structures and drying racks',
    ],
  },
]

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: 1,
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 101,
    crop_cycle_id: 1,
    category: 'irrigation',
    priority: 'high',
    action_title: 'Reduce irrigation schedule by 40% over next 48 hours',
    action_details: 'Soil moisture probes indicate 82% field capacity with incoming precipitation front. Curtail drip cycle to avoid root hypoxia.',
    rationale: 'Forecast predicts 8.5mm rainfall today followed by 12mm on Sept 15.',
    confidence_score: 0.94,
    evidence: ['Open-Meteo precipitation outlook: 20.5mm 5-day cumulative', 'Tensiometer readings: -15 kPa (near saturation)'],
    suggested_deadline: '2025-09-12',
    status: 'pending',
    created_at: '2025-09-11T05:30:00Z',
  },
  {
    id: 2,
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 101,
    crop_cycle_id: 1,
    category: 'pest_control',
    priority: 'medium',
    action_title: 'Monitor for Fall Armyworm scouting thresholds on Maize H6213',
    action_details: 'Current temperature and humidity conditions are in the optimal range (18-26°C, >70% RH) for oviposition.',
    rationale: 'Surrounding regional monitoring networks reported early instar larvae 12km west.',
    confidence_score: 0.88,
    evidence: ['Regional extension bulletin #44', 'Field microclimate within pest incubation sweet-spot'],
    suggested_deadline: '2025-09-14',
    status: 'pending',
    created_at: '2025-09-10T14:00:00Z',
  },
  {
    id: 3,
    farm_id: 2,
    farm_name: 'Mau Escarpment Terraces',
    field_id: 201,
    crop_cycle_id: 3,
    category: 'fertilizer',
    priority: 'urgent',
    action_title: 'Apply vegetative booster (Calcium Nitrate) on French Beans',
    action_details: 'Vegetative growth cycle at Day 42 requires supplemental nitrogen and soluble calcium for stem turgidity.',
    rationale: 'Leaf tissue chlorophyll reflectance sensor indicates slight vegetative chlorosis.',
    confidence_score: 0.91,
    evidence: ['NDVI index 0.61 vs target 0.74', 'Stage calendar: Pre-flowering vegetative push'],
    suggested_deadline: '2025-09-13',
    status: 'pending',
    created_at: '2025-09-11T07:15:00Z',
  },
]

export const MOCK_YIELD_ESTIMATES: YieldEstimate[] = [
  {
    id: 1,
    crop_cycle_id: 1,
    crop_name: 'White Maize (H6213)',
    farm_name: 'Green Ridge Highland Estate',
    predicted_yield_kg_ha: 5740,
    lower_bound_kg_ha: 5320,
    upper_bound_kg_ha: 6100,
    confidence_level: 0.89,
    prediction_model: 'AYIS-Ensemble-CropModel-v2 (GDD + Soil Moisture)',
    factors_analyzed: {
      weather_impact_pct: 32,
      soil_impact_pct: 44,
      management_impact_pct: 24,
    },
    generated_at: '2025-09-11T04:00:00Z',
  },
  {
    id: 2,
    crop_cycle_id: 3,
    crop_name: 'French Beans (Serengeti)',
    farm_name: 'Mau Escarpment Terraces',
    predicted_yield_kg_ha: 8350,
    lower_bound_kg_ha: 7900,
    upper_bound_kg_ha: 8800,
    confidence_level: 0.92,
    prediction_model: 'AYIS-Horticultural-YieldRegressor',
    factors_analyzed: {
      weather_impact_pct: 28,
      soil_impact_pct: 35,
      management_impact_pct: 37,
    },
    generated_at: '2025-09-10T18:00:00Z',
  },
]

export const MOCK_SUITABILITY: WeatherSuitability[] = [
  {
    farm_id: 1,
    crop_id: 1,
    suitability_score: 92,
    rating: 'optimal',
    limiting_factors: ['Slight night-time temperature drop in July'],
    temperature_suitability_score: 89,
    rainfall_suitability_score: 95,
    seasonal_outlook: 'Favorable condition throughout grain filling stage with minimal moisture stress.',
  },
  {
    farm_id: 1,
    crop_id: 2,
    suitability_score: 88,
    rating: 'optimal',
    limiting_factors: ['High humidity increases late blight risk'],
    temperature_suitability_score: 94,
    rainfall_suitability_score: 82,
    seasonal_outlook: 'Excellent tuber enlargement conditions; preventative fungicidal schedule advised.',
  },
]

export const MOCK_OBSERVATIONS: FieldObservation[] = [
  {
    id: 1,
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 101,
    field_name: 'North Terrace Block A',
    crop_name: 'White Maize (H6213)',
    growth_stage: 'Flowering & Pollination',
    observed_by: 'Sarah Mwangi (Agronomist)',
    observed_at: '2025-09-10T11:30:00Z',
    observation_type: 'pest',
    severity: 'mild',
    follow_up_status: 'monitoring',
    notes: 'Early instar Fall Armyworm larvae detected on 4% of sampled plant whorls. Below economic injury threshold but requires scouting in 72h.',
  },
  {
    id: 2,
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 102,
    field_name: 'Valley Bottom Block B',
    crop_name: 'Shangi Potato',
    growth_stage: 'Maturity / Post-Harvest',
    observed_by: 'Sarah Mwangi (Agronomist)',
    observed_at: '2025-08-28T09:00:00Z',
    observation_type: 'growth_milestone',
    severity: 'mild',
    follow_up_status: 'resolved',
    notes: 'Tuber skin set examination confirmed 98% hardening. Storage dormancy expected to hold for 75 days.',
  },
  {
    id: 3,
    farm_id: 2,
    farm_name: 'Mau Escarpment Terraces',
    field_id: 201,
    field_name: 'Ridge Plot 1',
    crop_name: 'French Beans (Serengeti)',
    growth_stage: 'Vegetative Growth',
    observed_by: 'Sarah Mwangi (Agronomist)',
    observed_at: '2025-09-11T08:15:00Z',
    observation_type: 'nutrient_deficiency',
    severity: 'moderate',
    follow_up_status: 'pending',
    notes: 'Interveinal chlorosis on youngest tri-foliates indicates rapid calcium/boron immobilization. Calcium nitrate foliar spray recommended.',
  },
]

export const MOCK_CROP_PROFILES: Record<number, CropProfile> = {
  1: {
    crop_id: 1,
    water_requirement_mm: 750,
    critical_growth_stages: ['Silking & Tasseling', 'Grain Filling', 'Early Vegetative'],
    common_pests: ['Fall Armyworm (Spodoptera frugiperda)', 'Maize Stalk Borer (Busseola fusca)', 'African Bollworm'],
    common_diseases: ['Maize Lethal Necrosis (MLND)', 'Northern Corn Leaf Blight', 'Grey Leaf Spot'],
    market_demand_rating: 'high',
    nutrient_requirements: {
      nitrogen_kg_ha: 120,
      phosphorus_kg_ha: 60,
      potassium_kg_ha: 40,
    },
  },
  2: {
    crop_id: 2,
    water_requirement_mm: 500,
    critical_growth_stages: ['Stolon Initiation', 'Tuber Bulking', 'Tuber Maturity'],
    common_pests: ['Potato Tuber Moth (Phthorimaea operculella)', 'Aphids (Myzus persicae)', 'Cutworms'],
    common_diseases: ['Late Blight (Phytophthora infestans)', 'Bacterial Wilt (Ralstonia solanacearum)', 'Blackleg'],
    market_demand_rating: 'high',
    nutrient_requirements: {
      nitrogen_kg_ha: 140,
      phosphorus_kg_ha: 90,
      potassium_kg_ha: 120,
    },
  },
  3: {
    crop_id: 3,
    water_requirement_mm: 400,
    critical_growth_stages: ['Flowering', 'Pod Elongation', 'Vegetative Canopy'],
    common_pests: ['Bean Thrips (Megalurothrips sjostedti)', 'Whiteflies (Bemisia tabaci)', 'Pod Borers'],
    common_diseases: ['Bean Rust (Uromyces appendiculatus)', 'Anthracnose', 'Angular Leaf Spot'],
    market_demand_rating: 'high',
    nutrient_requirements: {
      nitrogen_kg_ha: 60,
      phosphorus_kg_ha: 50,
      potassium_kg_ha: 60,
    },
  },
}

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n-1',
    recipient_id: 1,
    title: 'Pest Alert: Fall Armyworm',
    message: 'Early instar Fall Armyworm detected in North Terrace Block A (4% threshold).',
    type: 'alert',
    priority: 'high',
    read: false,
    link: '/dashboard/observations',
    created_at: '2025-09-11T09:00:00Z',
  },
  {
    id: 'n-2',
    recipient_id: 1,
    title: 'Advisory: Calcium Nitrate Application',
    message: 'Top-dressing recommended for French Beans ahead of flowering.',
    type: 'recommendation',
    priority: 'normal',
    read: false,
    link: '/dashboard/recommendations',
    created_at: '2025-09-10T14:30:00Z',
  },
  {
    id: 'n-3',
    recipient_id: 1,
    title: 'Weather Notice: Frost Watch',
    message: 'Micro-climate model forecasts temperatures dipping to 8°C Sunday dawn.',
    type: 'alert',
    priority: 'normal',
    read: true,
    link: '/dashboard/weather',
    created_at: '2025-09-09T18:00:00Z',
  },
]

export const MOCK_FIELD_VISITS: FieldVisit[] = [
  {
    id: 1,
    farmer_id: 3,
    farmer_name: 'Peter Otieno',
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 101,
    field_name: 'North Terrace Block A',
    officer_id: 6,
    officer_name: 'Brian Omondi',
    visit_date: '2025-09-12T09:30:00Z',
    purpose: 'Fall Armyworm scouting & bio-pesticide application verification',
    status: 'scheduled',
    notes: 'Bring pheromone trap refills and check lower whorls for second instar larvae.',
  },
  {
    id: 2,
    farmer_id: 4,
    farmer_name: 'Mary Wanjiku',
    farm_id: 2,
    farm_name: 'Mau Escarpment Terraces',
    field_id: 201,
    field_name: 'Ridge Plot 1',
    officer_id: 6,
    officer_name: 'Brian Omondi',
    visit_date: '2025-09-14T11:00:00Z',
    purpose: 'Soil runoff inspection and calcium nitrate top-dressing guidance',
    status: 'scheduled',
    notes: 'Verify terrace contour bund integrity ahead of heavy convective rain.',
  },
  {
    id: 3,
    farmer_id: 5,
    farmer_name: 'David Kiprono',
    farm_id: 3,
    farm_name: 'Kitale National Demonstration Farm',
    field_id: 102,
    field_name: 'Valley Bottom Block B',
    officer_id: 6,
    officer_name: 'Brian Omondi',
    visit_date: '2025-09-08T14:00:00Z',
    purpose: 'Post-harvest tuber grading & clean seed dormancy check',
    status: 'completed',
    notes: 'Completed full seed tuber inspection. Skin set verified at 98%.',
    findings_summary: 'Satisfactory compliance with certified seed protocols.',
  },
  {
    id: 4,
    farmer_id: 3,
    farmer_name: 'Peter Otieno',
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    field_id: 102,
    field_name: 'Valley Bottom Block B',
    officer_id: 6,
    officer_name: 'Brian Omondi',
    visit_date: '2025-09-16T10:00:00Z',
    purpose: 'Drip irrigation fertigation calibration',
    status: 'scheduled',
    notes: 'Farmer requested technical support to balance injector venturi pressure.',
  },
]

export const MOCK_FOLLOW_UPS: FollowUpTask[] = [
  {
    id: 1,
    farmer_id: 3,
    farmer_name: 'Peter Otieno',
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    title: 'Verify Fall Armyworm pheromone trap catches in Block A',
    task_type: 'risk_mitigation',
    priority: 'high',
    status: 'pending',
    due_date: '2025-09-13',
    description: 'Inspect 4 traps installed on North Terrace. If count exceeds 15 moths/night, recommend targeted neem oil or emamectin benzoate spray.',
    associated_observation_id: 1,
  },
  {
    id: 2,
    farmer_id: 4,
    farmer_name: 'Mary Wanjiku',
    farm_id: 2,
    farm_name: 'Mau Escarpment Terraces',
    title: 'Assist with French Beans calcium deficiency foliar mix',
    task_type: 'assistance_request',
    priority: 'critical',
    status: 'pending',
    due_date: '2025-09-12',
    description: 'Farmer requested technical verification on dosage for calcium nitrate foliar spray to stop interveinal leaf curling.',
    associated_observation_id: 3,
  },
  {
    id: 3,
    farmer_id: 5,
    farmer_name: 'David Kiprono',
    farm_id: 3,
    farm_name: 'Kitale National Demonstration Farm',
    title: 'Review terrace drainage clearance prior to heavy rain',
    task_type: 'scouting',
    priority: 'medium',
    status: 'pending',
    due_date: '2025-09-15',
    description: '15mm precipitation front advancing. Ensure farmer has unblocked terrace outlets to prevent water-logging.',
  },
  {
    id: 4,
    farmer_id: 3,
    farmer_name: 'Peter Otieno',
    farm_id: 1,
    farm_name: 'Green Ridge Highland Estate',
    title: 'Validate Shangi potato warehouse storage temperature',
    task_type: 'inspection',
    priority: 'low',
    status: 'completed',
    due_date: '2025-09-09',
    description: 'Checked ventilation and diffuse light storage racks. Storage temp maintained at 12°C.',
  },
]

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'LOG-89101',
    user_id: 1,
    username: 'admin_joseph',
    user_role: 'admin',
    action: 'USER_ROLE_UPDATED',
    resource: 'User',
    resource_id: '6 (officer_brian)',
    timestamp: '2026-09-11T14:45:10Z',
    status: 'SUCCESS',
    ip_address: '196.201.214.34',
    details: { updated_fields: ['role'], from: 'viewer', to: 'extension_officer' },
  },
  {
    id: 'LOG-89102',
    user_id: 2,
    username: 'agronomist_sarah',
    user_role: 'agronomist',
    action: 'CROP_PROFILE_MODIFIED',
    resource: 'CropProfile',
    resource_id: '1 (White Maize)',
    timestamp: '2026-09-11T13:20:00Z',
    status: 'SUCCESS',
    ip_address: '102.219.208.12',
    details: { parameter: 'optimal_rainfall_optimum_mm', new_value: 750 },
  },
  {
    id: 'LOG-89103',
    user_id: 6,
    username: 'officer_brian',
    user_role: 'extension_officer',
    action: 'FIELD_VISIT_CREATED',
    resource: 'FieldVisit',
    resource_id: '124',
    timestamp: '2026-09-11T11:05:42Z',
    status: 'SUCCESS',
    ip_address: '41.90.180.201',
    details: { farm: 'Mau Escarpment Terraces', farmer: 'Mary Wanjiku' },
  },
  {
    id: 'LOG-89104',
    user_id: 3,
    username: 'farmer_otieno',
    user_role: 'farmer',
    action: 'AUTH_FAILED',
    resource: 'Auth',
    timestamp: '2026-09-11T09:12:15Z',
    status: 'FAILED',
    ip_address: '105.161.14.88',
    details: { reason: 'Invalid credential signature (attempt 2 of 5)' },
  },
  {
    id: 'LOG-89105',
    user_id: 1,
    username: 'admin_joseph',
    user_role: 'admin',
    action: 'WEATHER_SOURCE_RESYNC',
    resource: 'WeatherSource',
    resource_id: 'WS-SRC-01',
    timestamp: '2026-09-11T08:00:00Z',
    status: 'SUCCESS',
    ip_address: '196.201.214.34',
    details: { stations_polled: 5, records_ingested: 288 },
  },
  {
    id: 'LOG-89106',
    user_id: 0,
    username: 'system_daemon',
    user_role: 'system',
    action: 'DATA_QUALITY_ANOMALY_FLAG',
    resource: 'DataQuality',
    resource_id: 'WS-KER-05',
    timestamp: '2026-09-11T07:15:30Z',
    status: 'WARNING',
    ip_address: '127.0.0.1',
    details: { sensor: 'relative_humidity', value: '104.2%', clamp: '100.0%' },
  },
  {
    id: 'LOG-89107',
    user_id: 5,
    username: 'farmer_kiprono',
    user_role: 'farmer',
    action: 'PASSWORD_RESET_REQUEST',
    resource: 'Auth',
    timestamp: '2026-09-10T18:40:11Z',
    status: 'SUCCESS',
    ip_address: '197.232.88.5',
    details: { token_sent: 'SMS Gateway +254 733 456 789' },
  },
]

export const MOCK_SYSTEM_HEALTH: SystemServiceHealth[] = [
  {
    name: 'Core Application & Frontend Gateway',
    category: 'core',
    status: 'operational',
    uptime_pct: 99.98,
    latency_ms: 38,
    last_check: '2026-09-11T14:55:00Z',
    version: 'v1.4.2-prod',
    error_count_24h: 0,
    warning_count_24h: 2,
    notes: 'Next.js 15 App Router Edge runtime operational with Tauri desktop IPC hook.',
  },
  {
    name: 'Weather Ingestion & Mesh Reanalysis',
    category: 'weather',
    status: 'operational',
    uptime_pct: 99.74,
    latency_ms: 142,
    last_check: '2026-09-11T14:54:30Z',
    version: 'v2.1.0',
    error_count_24h: 1,
    warning_count_24h: 8,
    notes: 'Open-Meteo API downlink active. 5 automated field stations syncing on 15-second intervals.',
  },
  {
    name: 'PostgreSQL / Django ORM Core Database',
    category: 'database',
    status: 'operational',
    uptime_pct: 100.0,
    latency_ms: 12,
    last_check: '2026-09-11T14:55:10Z',
    version: 'PostgreSQL 16.3',
    error_count_24h: 0,
    warning_count_24h: 0,
    notes: 'Connection pool 24/60 active connections. Zero deadlocks or slow query breaches.',
  },
  {
    name: 'JWT Authentication & RBAC Service',
    category: 'auth',
    status: 'operational',
    uptime_pct: 99.99,
    latency_ms: 45,
    last_check: '2026-09-11T14:55:00Z',
    version: 'v1.0.4',
    error_count_24h: 2,
    warning_count_24h: 3,
    notes: 'Role-based permission matrix active for 7 user categories.',
  },
  {
    name: 'Agricultural Yield & ML Inference Engine',
    category: 'ai_engine',
    status: 'operational',
    uptime_pct: 99.45,
    latency_ms: 280,
    last_check: '2026-09-11T14:53:00Z',
    version: 'Ensemble XGBoost-FAO56 v3.2',
    error_count_24h: 0,
    warning_count_24h: 5,
    notes: 'Yield simulations cached for current active cycles. Background retraining scheduled Sunday 02:00 UTC.',
  },
]

export const MOCK_WEATHER_SOURCES: WeatherSourceConfig[] = [
  {
    id: 'WS-SRC-01',
    name: 'Automated Ground Telemetry Mesh (Davis/Campbell/Vaisala)',
    provider: 'telemetry_mesh',
    status: 'active',
    update_frequency_minutes: 1,
    last_sync_timestamp: '2026-09-11T14:55:00Z',
    api_endpoint: 'mqtt://telemetry.ayi-platform.org:8883/stations/stream',
    monitored_locations_count: 5,
    thresholds: {
      frost_temp_c: 4.0,
      extreme_heat_temp_c: 32.0,
      heavy_rain_mm_hr: 15.0,
      high_wind_ms: 16.0,
      dry_spell_consecutive_days: 14,
    },
  },
  {
    id: 'WS-SRC-02',
    name: 'Open-Meteo High Resolution African Mesh (ECMWF IFS 9km)',
    provider: 'open_meteo',
    status: 'active',
    update_frequency_minutes: 60,
    last_sync_timestamp: '2026-09-11T14:00:00Z',
    api_endpoint: 'https://api.open-meteo.com/v1/forecast',
    monitored_locations_count: 18,
    thresholds: {
      frost_temp_c: 5.0,
      extreme_heat_temp_c: 33.0,
      heavy_rain_mm_hr: 20.0,
      high_wind_ms: 18.0,
      dry_spell_consecutive_days: 12,
    },
  },
  {
    id: 'WS-SRC-03',
    name: 'Copernicus Climate Data Store (ERA5-Land Reanalysis)',
    provider: 'copernicus_era5',
    status: 'standby',
    update_frequency_minutes: 360,
    last_sync_timestamp: '2026-09-11T12:00:00Z',
    api_endpoint: 'https://cds.climate.copernicus.eu/api/v2',
    monitored_locations_count: 32,
    thresholds: {
      frost_temp_c: 3.5,
      extreme_heat_temp_c: 34.0,
      heavy_rain_mm_hr: 25.0,
      high_wind_ms: 20.0,
      dry_spell_consecutive_days: 15,
    },
  },
]

export const MOCK_SYSTEM_SETTINGS: SystemSettings = {
  organization_name: 'Kenya Agricultural & Yield Intelligence Services (AYIS)',
  platform_mode: 'production',
  default_language: 'en-KE (English / Swahili Ready)',
  time_zone: 'Africa/Nairobi (EAT, UTC+3)',
  unit_temperature: 'celsius',
  unit_rainfall: 'mm',
  unit_area: 'hectares',
  unit_yield: 'kg_ha',
  email_notifications_enabled: true,
  sms_alerts_enabled: true,
  auto_recommendation_interval_hours: 12,
  telemetry_sync_rate_seconds: 15,
  max_login_attempts: 5,
  session_timeout_minutes: 60,
}


